ministryofjustice/send-legal-mail-to-prisons

.gitignore
README.md
docker-compose.yml
feature.env
helm_deploy/send-legal-mail-to-prisons/values.yaml
package.json
server/data/hmppsAuthClient.test.ts
server/data/hmppsAuthClient.ts
server/index.ts
server/services/userService.test.ts

* Add readme
* Remove system client

403 tidy up skeleton

---

server/config.ts
server/middleware/setUpWebSecurity.ts
server/middleware/setUpWebSession.ts
server/views/partials/layout.njk

403 Add Google Tag Manager support

---

server/config.ts
server/middleware/setUpWebSession.ts
server/views/partials/layout.njk

403 Make Google Analytics optional

---

package-lock.json
package.json
server/@types/express/index.d.ts
server/@types/forms/index.d.ts
server/app.ts
server/middleware/setupRequestLink.ts
server/routes/link/RequestLinkController.ts
server/routes/link/RequestLinkView.ts
server/routes/testutils/appSetup.ts
server/utils/nunjucksSetup.ts
server/views/autherror.njk
server/views/layout.njk
server/views/pages/error.njk
server/views/pages/index.njk
server/views/pages/link/requestLink.njk
server/views/pages/link/requestLink.test.ts

e1s1 - add request link screen

---

integration_tests/integration/link/requestLink.spec.ts
integration_tests/pages/link/emailSent.ts
integration_tests/pages/link/requestLink.ts
integration_tests/pages/page.ts
server/@types/express/index.d.ts
server/app.ts
server/middleware/link/setupRequestLink.ts
server/routes/link/RequestLinkController.ts
server/routes/link/RequestLinkValidator.test.ts
server/routes/link/RequestLinkValidator.ts
server/utils/nunjucksSetup.ts
server/views/pages/link/emailSent.njk
server/views/pages/link/requestLink.njk

e1s1 - add basic submit

---

integration_tests/integration/link/emailSent.spec.ts
integration_tests/integration/link/requestLink.spec.ts
integration_tests/pages/link/emailSent.ts
integration_tests/pages/link/requestLink.ts
server/views/layout.njk
server/views/pages/link/emailSent.njk
server/views/partials/header.njk

e1s1 - use descriptive methods in Cypress tests

---

integration_tests/mockApis/sendLegalMail.ts
server/middleware/barcode/barcodeAuthorisationMiddleware.ts
server/routes/link/RequestLinkController.ts
server/routes/link/VerifyLinkController.ts

Added debug; corrected response spec in mockAPI for /link/verify; corrected promise return in controllers

Added debug

---

package-lock.json
server/middleware/barcode/barcodeAuthorisationMiddleware.ts

SLM-14 session expiry

---

integration_tests/integration/index.spec.ts
integration_tests/integration/login.spec.ts
integration_tests/integration/scan/scanBarcode.spec.ts
integration_tests/mockApis/auth.ts
integration_tests/pages/authorisationError.ts
integration_tests/pages/index.ts
integration_tests/pages/scan/scanBarcode.ts
integration_tests/plugins/index.ts
server/@types/express/index.d.ts
server/@types/forms/index.d.ts
server/app.ts
server/middleware/populateCurrentUserRoles.ts
server/middleware/scan/setupScanBarcode.ts
server/routes/index.test.ts
server/routes/index.ts
server/routes/landingPageTiles.ts
server/routes/scan/ScanBarcodeController.ts
server/routes/scan/ScanBarcodeView.ts
server/routes/standardRouter.ts
server/routes/testutils/appSetup.ts
server/views/components/card/card.njk
server/views/pages/index.njk
server/views/pages/scan/scan-barcode.njk

Landing page tile for Scan Barcode; placeholder Scan Barcode page; cypress tests

SLM-29: Landing page tile for Scan Barcode

---

integration_tests/integration/link/emailSent.spec.ts
server/app.ts
server/middleware/link/setupLinkEmailSent.ts
server/routes/link/LinkEmailSentController.ts
server/routes/link/RequestLinkController.ts

Added new controller to implement post-redirect pattern to fix browser refresh problem on email sent page

SLM-29: Fix browser refresh problem on email sent page

---

integration_tests/integration/scan/manuallyEnterBarcode.spec.ts
integration_tests/integration/scan/reportManualBarcodeEntryProblem.spec.ts
integration_tests/pages/scan/manualBarcodeEntry.ts
integration_tests/pages/scan/reportManualBarcodeEntryProblem.ts
server/middleware/scan/setupScanBarcode.ts
server/routes/scan/ManualEntryBarcodeController.ts
server/views/pages/link/emailSent.njk
server/views/pages/link/requestLink.njk
server/views/pages/scan/manual-barcode-entry.njk
server/views/pages/scan/report-manual-barcode-entry-problem.njk
server/views/pages/scan/scan-barcode.njk

Added placeholder page for reporting problem manually entering barcode
Also minor update to existing pages to fix minor accessibility problem

SLM-9: Added placeholder page for reporting problem manually entering barcode

---

README.md
docker-compose.yml
integration_tests/integration/barcode/findRecipientCreateBarcode.spec.ts
integration_tests/integration/link/requestLink.spec.ts
integration_tests/integration/scan/scanBarcode.spec.ts
integration_tests/pages/page.ts
package-lock.json
package.json
server/routes/index.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/index.njk
server/views/partials/header.njk

External users only see pages under /link and /barcode with title "Send Legal Mail To Prisons".
Internal users see any other pages with title "Check Rule 39 Mail".

SLM-37 Internal and external user page titles

---

helm_deploy/send-legal-mail-to-prisons/templates/_helpers.tpl
helm_deploy/send-legal-mail-to-prisons/templates/ingress.yaml
helm_deploy/send-legal-mail-to-prisons/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

Add custom ingresses to allow different URLs for internal / external users.

SLM-37 internal and external ingress

---

README.md
assets/js/page-enhancements.js
docker-compose.yml
package-lock.json
package.json
server/middleware/setUpStaticResources.ts
server/routes/barcode/FindRecipientView.test.ts
server/routes/barcode/FindRecipientView.ts
server/views/layout.njk
server/views/pages/barcode/find-recipient.njk

This PR changes the prison dropdown to an autocomplete / type-ahead if the user has JS enabled (progressive enhancement)
It also updates the docker-compose file to bring in the prison-register image when running locally, and it applys a sort order to the prison list

SLM-73: Added autocomplete for prison field

---

integration_tests/integration/barcode/createBarcodeAddressImage.spec.ts
integration_tests/pages/barcode/chooseBarcodeOption.ts
integration_tests/pages/barcode/generateBarcodeImage.ts
integration_tests/pages/barcode/reviewRecipients.ts
server/@types/express/index.d.ts
server/@types/forms/index.d.ts
server/middleware/barcode/setupBarcode.ts
server/routes/barcode/ChooseBarcodeOptionController.test.ts
server/routes/barcode/ChooseBarcodeOptionController.ts
server/routes/barcode/ChooseBarcodeOptionView.ts
server/routes/barcode/GenerateBarcodeImageController.test.ts
server/routes/barcode/GenerateBarcodeImageController.ts
server/routes/barcode/barcodeOptionValidator.test.ts
server/routes/barcode/barcodeOptionValidator.ts
server/views/pages/barcode/choose-barcode-option.njk
server/views/pages/barcode/choose-barcode-option.test.ts
server/views/pages/barcode/review-recipients.njk

Added new page after Review Recipients to select either a barcode address image or a coversheet.
TODO add in the images to the radio button - currently just text

SLM-69 choose barcode print type

---

integration_tests/integration/barcode/createBarcodeAddressImage.spec.ts
integration_tests/pages/barcode/generateBarcodeImage.ts
server/routes/barcode/image/GenerateBarcodeImageController.test.ts
server/routes/barcode/image/GenerateBarcodeImageController.ts
server/routes/barcode/image/GenerateBarcodeImageView.ts
server/views/pages/barcode/generate-barcode-image.njk

SLM-78: Render multiple barcode images

---

server/@types/forms/index.d.ts
server/@types/prisonTypes.ts
server/middleware/barcode/setupBarcode.ts
server/routes/barcode/contacts/CreateContactByPrisonNumberController.test.ts
server/routes/barcode/contacts/CreateContactByPrisonNumberController.ts
server/routes/barcode/contacts/CreateContactByPrisonerNameController.test.ts
server/routes/barcode/contacts/CreateContactByPrisonerNameController.ts
server/routes/barcode/contacts/newContactByPrisonerNameValidator.test.ts
server/routes/barcode/recipients/FindRecipientController.test.ts
server/routes/barcode/recipients/FindRecipientController.ts
server/routes/barcode/validators/prisonerDobValidator.test.ts
server/routes/barcode/validators/prisonerDobValidator.ts

* renamed some long method names that were obvious by their class
* add date handling to new pages capturing by name and dob
* Plumb in new pages

SLM-81 new screen plumbing

---

assets/js/page-enhancements.js
integration_tests/integration/barcode/createNewContactByPrisonNumber.spec.ts
integration_tests/integration/barcode/createNewContactByPrisonerName.spec.ts
integration_tests/pages/barcode/createNewContactByPrisonNumber.ts
integration_tests/pages/barcode/createNewContactByPrisonerName.ts
integration_tests/pages/barcode/findRecipientByPrisonNumber.ts
integration_tests/pages/barcode/findRecipientByPrisonerName.ts
server/routes/barcode/recipients/FindRecipientController.test.ts
server/routes/barcode/recipients/FindRecipientController.ts
server/views/pages/barcode/review-recipients.njk

* Don't save prisoner name from previous form, it is no longer relevant
* Fix autofocus - errors first, or first field

SLM-81 fixes

---

assets/js/page-enhancements.js
integration_tests/integration/barcode/createNewContactByPrisonNumber.spec.ts
integration_tests/integration/barcode/createNewContactByPrisonerName.spec.ts
package-lock.json

* Autofocus usage is questionable at best - go back to original design while we challenge its inclusion
* npm update

SLM-81 autofocus errors

---

assets/js/page-enhancements.js
integration_tests/integration/e2e/legalSenderJourneyE2e.spec.ts
integration_tests/pages/barcode/createNewContactByPrisonNumber.ts
integration_tests/pages/barcode/createNewContactByPrisonerName.ts
integration_tests/pages/barcode/findRecipientByPrisonNumber.ts
integration_tests/pages/barcode/findRecipientByPrisonerName.ts
server/routes/barcode/image/GenerateBarcodeImageController.ts
server/routes/barcode/pdf/PdfController.test.ts
server/routes/barcode/pdf/PdfController.ts

* give pdfs a generic filename
* prevent update of recipients after barcode documents are generated
* remove autofocus unless essential, it's a bit rubbish

SLM-79 pdfs

---

package-lock.json
server/@types/sendLegalMailApi/index.d.ts
server/services/contacts/ContactService.spec.ts
server/services/contacts/ContactService.ts
server/views/pages/barcode/choose-barcode-option.njk
server/views/pages/barcode/create-new-contact-by-prison-number.njk
server/views/pages/barcode/create-new-contact-by-prisoner-name.njk
server/views/pages/barcode/pdf/select-envelope-size.njk

Plus remove HTML5 validation and npm update

SLM-62 search contact api

---

server/@types/express/index.d.ts
server/@types/forms/index.d.ts
server/@types/sendLegalMailApiClientTypes.ts
server/filters/renderChooseContactRadiosFilter.ts
server/routes/barcode/contacts/ChooseContactController.test.ts
server/routes/barcode/contacts/ChooseContactController.ts
server/routes/barcode/contacts/ChooseContactView.ts
server/services/contacts/ContactService.spec.ts
server/services/contacts/ContactService.ts

(These are not plumbed in yet!)

SLM-62 Add controller and view for choose contact page

---

server/config.ts
server/utils/nunjucksSetup.ts
server/views/pages/barcode/generate-barcode-image.njk
server/views/pages/barcode/pdf/print-coversheets.njk

"Inspired by" ;) what the good folk in CVL have done for this

SLM-59: Wired in feedback links

---

integration_tests/integration/barcode/findRecipientByPrisonerName.spec.ts
integration_tests/integration/e2e/legalSenderJourneyE2e.spec.ts
integration_tests/mockApis/sendLegalMail.ts
integration_tests/pages/barcode/chooseContact.ts
integration_tests/pages/barcode/createNewContactByPrisonerName.ts
integration_tests/pages/barcode/findRecipientByPrisonerName.ts
integration_tests/plugins/index.ts
server/middleware/barcode/setupBarcode.ts
server/routes/barcode/contacts/ChooseContactController.test.ts
server/routes/barcode/contacts/ChooseContactController.ts
server/routes/barcode/contacts/CreateContactByPrisonerNameController.test.ts
server/routes/barcode/contacts/CreateContactByPrisonerNameController.ts
server/routes/barcode/recipients/FindRecipientController.test.ts
server/routes/barcode/recipients/FindRecipientController.ts
server/views/pages/barcode/choose-contact.njk
server/views/pages/barcode/choose-contact.test.ts

* place choose contact page after find recipient by name
* tidy up some contact id processing
* add choose contacts to the integration tests

SLM-62 plumb in new choose contacts page

---

integration_tests/integration/barcode/findRecipientByPrisonerName.spec.ts
server/@types/sendLegalMailApi/index.d.ts
server/routes/barcode/recipients/FindRecipientController.test.ts
server/routes/barcode/recipients/FindRecipientController.ts
server/services/contacts/ContactService.spec.ts
server/services/contacts/ContactService.ts

Integration tests coming next (they still work only because our error handling ignores failing contact lookup!)

SLM-121 Look for existing contact before creating a new one

---

server/app.ts
server/middleware/helpdesk/setupContactHelpdesk.ts
server/routes/helpdesk/ContactHelpdeskController.ts
server/utils/nunjucksSetup.ts
server/views/layout.njk
server/views/pages/helpdesk/contact-helpdesk.njk

SLM-106: Render basic view for contact helpdesk form

---

server/middleware/helpdesk/setupContactHelpdesk.ts
server/routes/helpdesk/ContactHelpdeskController.test.ts
server/routes/helpdesk/ContactHelpdeskController.ts
server/routes/helpdesk/contactHelpdeskFormValidator.test.ts
server/routes/helpdesk/contactHelpdeskFormValidator.ts
server/routes/helpdesk/validators/emailValidator.test.ts
server/routes/helpdesk/validators/emailValidator.ts
server/routes/helpdesk/validators/nameValidator.test.ts
server/routes/helpdesk/validators/nameValidator.ts
server/routes/helpdesk/validators/problemDetailValidator.test.ts
server/routes/helpdesk/validators/problemDetailValidator.ts
server/utils/nunjucksSetup.ts
server/views/pages/helpdesk/contact-helpdesk.njk
server/views/pages/helpdesk/submitted.njk

SLM-106: Validate contact-helpdesk form, redirect to submitted page

---

server/app.ts
server/middleware/start/setupLegalSenderStartPage.ts
server/views/pages/start/legal-sender-start-page.njk

SLM-131: legal sender start page

---

server/@types/forms/index.d.ts
server/middleware/barcode/setupBarcode.ts
server/routes/barcode/contacts/EditContactController.test.ts
server/routes/barcode/contacts/EditContactController.ts
server/routes/barcode/contacts/EditContactView.ts
server/views/pages/barcode/create-new-contact-by-prison-number.njk
server/views/pages/barcode/create-new-contact-by-prisoner-name.njk
server/views/pages/barcode/edit-contact-details.njk
server/views/pages/barcode/edit-contact-details.test.ts

Display the new page - load and save details coming soon

SLM-63 New edit contact page

---

integration_tests/mockApis/sendLegalMail.ts
server/@types/sendLegalMailApi/index.d.ts
server/middleware/barcode/setupBarcode.ts
server/routes/barcode/contacts/EditContactController.ts
server/routes/barcode/recipients/FindRecipientController.test.ts
server/routes/barcode/recipients/FindRecipientController.ts
server/services/contacts/ContactService.spec.ts
server/services/contacts/ContactService.ts

And move /contact/{prisonNumber} to /contact/prisonNumber/{prisonNumber}
(/contact/id/{id} will be moved to /contact/{id} when that URL becomes free)

SLM-63 New endpoint /contact/id/{id}

---

package-lock.json

PR to fix https://app.circleci.com/pipelines/github/ministryofjustice/send-legal-mail-to-prisons/659/workflows/0a798a24-56ed-4fdd-b3c5-43acea95e9fc/jobs/3034

Ran `npm update` to update dependencies

---

assets/sass/local.sass
integration_tests/pages/barcode/reviewRecipients.ts
server/filters/recipientTableRowsFilter.test.ts
server/filters/recipientTableRowsFilter.ts
server/views/pages/barcode/create-new-contact-by-prisoner-name.njk
server/views/pages/barcode/edit-contact-details.njk
server/views/pages/barcode/generate-barcode-image.njk
server/views/pages/barcode/review-recipients.njk
server/views/pages/link/emailSent.njk
server/views/pages/link/requestLink.njk

Various changes following a design review

SLM-162 UI updates

---

server/views/pages/barcode/create-new-contact-by-prisoner-name.njk
server/views/pages/barcode/edit-contact-details.njk
server/views/pages/barcode/generate-barcode-image.njk

Back out some design changes after designer testing

SLM-162 fixes

---

.circleci/config.yml
package-lock.json

SLM-190 Get smoke test secrets from correct env

---

integration_tests/smoke/smoke.spec.ts

Attempt to prevent flaky tests.

SLM-190 smoke test

---

Dockerfile
package-lock.json
server/@types/sendLegalMailApi/index.d.ts
server/@types/sendLegalMailApiClient/index.d.ts
server/services/cjsm/CjsmService.test.ts
server/services/cjsm/CjsmService.ts

* and npm update
* and fix to docker layer caching issue

SLM-202 cjsm user details client

---

assets/js/page-enhancements.js
server/views/pages/barcode/generate-barcode-image.njk
server/views/pages/barcode/pdf/print-coversheets.njk
server/views/pages/scan/scan-barcode-result.njk

I didn't want to add this to layout.njk as it doesn't apply to all pages - so I'm trying this method of pushing to GA using JS.

SLM-202 additional GA data

---

assets/js/page-enhancements.js
server/views/layout.njk
server/views/layout.test.ts
server/views/pages/barcode/generate-barcode-image.njk
server/views/pages/barcode/pdf/print-coversheets.njk
server/views/pages/scan/scan-barcode-result.njk

Using JS to push to Google Analytics fails - seems to be sending requests to gtm out of sync.
Revert back to the proven method - push to gtm before gtm consent is initialised

SLM-202 fix ga timing

---

server/app.ts
server/views/partials/header.njk

PR to use the correct sign-out link based on whether we are using magic link auth or one time code auth

SLM-231: Correct sign out link based on whether using magic link or one time code

---

server/@types/forms/index.d.ts
server/middleware/one-time-code-auth/setUpOneTimeCode.ts
server/middleware/one-time-code-auth/setupVerifyOneTimeCode.ts
server/routes/one-time-code-auth/OneTimeCodeEmailSentController.test.ts
server/routes/one-time-code-auth/OneTimeCodeEmailSentController.ts
server/routes/one-time-code-auth/OneTimeCodeEmailSentView.ts
server/routes/one-time-code-auth/RequestOneTimeCodeController.ts
server/routes/one-time-code-auth/VerifyOneTimeCodeController.test.ts
server/routes/one-time-code-auth/VerifyOneTimeCodeController.ts
server/services/one-time-code-auth/OneTimeCodeService.test.ts
server/services/one-time-code-auth/OneTimeCodeService.ts

The PR implements and wires in the service code to call the API to verify a one time code

SLM-231: Fleshed out service call to verify a one time code

---

helm_deploy/values-dev.yaml
server/app.ts
server/config.ts
server/routes/one-time-code-auth/RequestOneTimeCodeController.test.ts
server/routes/one-time-code-auth/RequestOneTimeCodeView.ts
server/utils/nunjucksSetup.ts
server/views/pages/one-time-code-auth/requestOneTimeCode.njk

Page layout and content for the initial Request One Time Code page:

SLM-231: Request Code page layout and content as per designs

---

server/routes/one-time-code-auth/OneTimeCodeEmailSentController.test.ts
server/routes/one-time-code-auth/OneTimeCodeEmailSentView.ts
server/views/pages/one-time-code-auth/emailSent.njk

Page layout and content for the Email Sent / Enter Code page:

SLM-231: Email Sent page layout and content as per designs

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

PR to enable One Time Code authentication in dev and preprod via the environment variable feature flag

SLM-231: Enabled One Time Code in dev and preprod

---

server/filters/pageTitleInErrorFilter.test.ts
server/filters/pageTitleInErrorFilter.ts
server/utils/nunjucksSetup.ts
server/views/layout.njk
server/views/pages/barcode/create-new-contact-by-prison-number.njk
server/views/pages/barcode/create-new-contact-by-prisoner-name.njk
server/views/pages/barcode/find-recipient-by-prison-number.njk
server/views/pages/barcode/find-recipient-by-prisoner-name.njk
server/views/pages/barcode/generate-barcode-image.njk
server/views/pages/barcode/pdf/print-coversheets.njk
server/views/pages/link/emailSent.njk

* improve text on page titles for screen readers
* add error prefix to page titles if page has errors

SLM-222 page titles

---

README.md
docker-compose.yml
integration_tests/integration/e2e/legalSenderJourneyE2e.spec.ts
integration_tests/pages/barcode/reviewRecipients.ts
server/middleware/barcode/setupBarcode.ts
server/routes/barcode/review/ReviewRecipientsController.test.ts
server/routes/barcode/review/ReviewRecipientsController.ts
server/views/pages/barcode/review-recipients.njk
server/views/pages/barcode/review-recipients.test.ts

Switch the template for Review Recipients to use the new radio button instead of the old link.

SLM-236 another recipient radio button

---

server/filters/formatDateFilter.test.ts
server/filters/formatDateFilter.ts
server/filters/formatDateForResultsPageFilter.ts
server/filters/formatDateTimeForResultsPageFilter.ts
server/utils/nunjucksSetup.ts
server/views/partials/scan/scan-barcode-result-duplicate.njk
server/views/partials/scan/scan-barcode-result-duplicate.test.ts
server/views/partials/scan/scan-barcode-result-expired.njk

SLM-152: Added generic formatDate filter and used in views

---

README.md

Mainly with alerting and monitoring info

SLM-250 update readme

---

package-lock.json
server/app.ts
server/filters/prisonsTableRowFilter.test.ts
server/filters/prisonsTableRowsFilter.ts
server/middleware/prisons/setupSupportedPrisons.ts
server/routes/prisons/SupportedPrisonsController.test.ts
server/routes/prisons/SupportedPrisonsController.ts
server/routes/prisons/SupportedPrisonsView.ts
server/views/pages/prisons/supported-prisons.njk
server/views/pages/prisons/supported-prisons.test.ts

For Manage supported prisons:
* Add prison names to the table
* Add a dropdown to select a new prison

SLM-253 prison names

---

server/app.ts
server/index.ts
server/middleware/prisons/setupSupportedPrisons.ts
server/routes/prisons/SupportedPrisonsController.test.ts
server/routes/prisons/SupportedPrisonsController.ts
server/services/prison/PrisonService.test.ts
server/services/prison/PrisonService.ts

* introduce new PrisonService that will become a facade for PrisonRegisterService and SupportedPrisonService
* implement PrisonService in the SupportedPrisonsController
* a future PR will replace all occurences of PrisonRegisterService and config.supportedPrisons

SLM-253 new PrisonService

---

server/middleware/scan/setupScanBarcode.ts

Add async middleware to ensure unexpected API responses from SLM backend (e.g. 401/403) are ultimately passed to error handler rather than crashing the application.

SLM:261: Improve error handling in scan barcode routes

---

integration_tests/integration/accessibility-statement/accessibility-statement.spec.ts
integration_tests/pages/accessibility-statement/accessibilityStatement.ts
server/app.ts
server/utils/nunjucksSetup.ts
server/views/layout.njk
server/views/pages/accessibility-statement/accessibility-statement.njk

* add accessibility statement page and integration test
* include footer link - only for legal sender pages

SLM-262: Add accessibility statement

---

package-lock.json
package.json

Update to typescript dependency version as a fix for security failures.

Update typescript dependency version.

---

package-lock.json
package.json

Major updates to @ministryofjustice/frontend, govuk-frontend and sass versions.

Major updates to frontend dependency versions.

---

server/config.ts

Update feedback link to https://send-legal-mail-to-prisons.form.service.justice.gov.uk/ to allow usage of MOJ forms.

Update feedback link on SLM - staff and public facing

---

server/utils/azureAppInsights.test.ts
server/utils/azureAppInsights.ts

Changes done based on instructions here - https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/4373872770/How+to+collect+usage+by+establishment+via+App+insights
Sample change - 
https://github.com/ministryofjustice/use-of-force/pull/599/files

SLM-292 changes - add user and caseload to request.

---

server/views/pages/privacy-policy/privacy-policy.njk

Updates to Privacy Policy

---

server/views/pages/cookies/cookies-policy.njk

Updated the cookie page to add reference to MOJ forms and generally tidy up.

Updated cookie page

---

server/views/pages/accessibility-statement/accessibility-statement.njk

Corrected generic email address

Corrected generic email address

---

server/views/pages/one-time-code-auth/requestOneTimeCode.njk
server/views/pages/one-time-code-auth/requestOneTimeCode.test.ts
server/views/pages/start/legal-sender-start-page.njk
server/views/pages/start/legal-sender-start-page.test.ts

Update to the start and one-time code pages to improve visibility of the need for a CJSM email account.

Slm 348 add link to how to sign up to cjsm on homepage

---

package-lock.json
package.json
server/@types/express/index.d.ts
server/middleware/setUpWebSession.ts

Original PR here https://github.com/ministryofjustice/hmpps-template-typescript/pull/67/files

Remove express-session-id dependency as per template in 2022

---

package-lock.json
package.json

Major change but no effect on our usage

Update audit-ci to v7

---

server/views/pages/privacy-policy/privacy-policy.njk

Updates includes changes to indicate we are using GOV.UK Notify. 
SLM-365

Updated privacy policy SLM-365

---

.circleci/config.yml

Just remove the check, we don't use it any more.

Remove check outdated

---

package-lock.json
package.json

Updates both MOJ and GOV.UK Frontend packages in preparation for new GOV.UK rebrand

Updates both MOJ and GOV.UK Frontend packages
