integration_tests/integration/link/emailSent.spec.ts
integration_tests/integration/link/requestLink.spec.ts
integration_tests/integration/link/verifyLink.spec.ts
integration_tests/mockApis/sendLegalMail.ts
integration_tests/pages/link/emailSent.ts
integration_tests/plugins/index.ts
server/config.ts
server/middleware/barcode/barcodeAuthorisationMiddleware.ts
server/routes/link/RequestLinkController.ts
server/routes/link/RequestLinkValidator.test.ts
server/routes/link/RequestLinkValidator.ts
server/routes/link/RequestLinkView.ts
server/routes/link/VerifyLinkController.ts
server/views/pages/link/emailSent.njk
server/views/pages/link/requestLink.njk

This PR updates the screen copy and validation messages for the Request A Link page and Email Sent page, based on the latest copy from the design team.
Things of note:
* The Email Sent page has changed in that it no longer has a field to allow retrying to send the email, and instead has a link to take you back to the Request A Link page. Therefore the integration tests and associated Page class have changed quite a bit.
* The assertions in the integration tests re: error messaging have been simplified and made more generic, testing more that an error message is present rather than the specifics of the precise wording of the error message (ie. they were fragile before)
* Added error handling from the API when the supplied email address is not a CJSM email, and added an integration test for …

Updated validation messages and screen copy

---

helm_deploy/send-legal-mail-to-prisons/values.yaml
helm_deploy/values-preprod.yaml

We're having issues with team members being blocked with 403s. I don't understand how the mesh of MOJ networks hangs together but we keep finding new and exciting ways to be blocked. The UI will be public anyway so just turning off the allow list completely.

SLM remove allow list

---

server.ts
server/app.ts
server/index.ts
server/middleware/scan/setupScanBarcode.ts
server/routes/scan/ScanBarcodeController.ts
server/services/AppInsightsService.ts

Refactored the way the express `app` is created so that the appInsights `TelemetryClient` can be created once (before the app) and injected into the app

SLM-8: Track 'report barcode entry problem' event via AppInsights

---

integration_tests/integration/e2e/mailroomJourneyE2e.spec.ts
integration_tests/pages/scan/manualBarcodeEntry.ts
integration_tests/pages/scan/scanBarcodeResult.ts
server/views/pages/scan/manual-barcode-entry.njk
server/views/pages/scan/scan-barcode-result.njk
server/views/pages/scan/scan-barcode.njk

The fix for the 404s was to add a slash/root prefix on the action url of the 'scan again' forms

SLM-70: Fixed 404s on result page; added e2e journey test

---

README.md
package-lock.json
package.json
server/@types/express/index.d.ts
server/middleware/setUpWebSecurity.ts
server/routes/barcode/CreateBarcodeController.ts
server/routes/barcode/FindRecipientController.ts
server/routes/barcode/FindRecipientView.ts
server/views/pages/barcode/find-recipient.njk

Shows the barcode on screen when you generate a new barcode from the legal mail sender sign in.
This barcode will be removed from the screen and added to the printed documents in future stories.

SLM-72 generate barcode image

---

server/@types/prisonTypes.ts
server/data/cache/PrisonRegisterStore.test.ts
server/data/cache/PrisonRegisterStore.ts
server/index.ts
server/routes/barcode/FindRecipientView.ts
server/services/prison/PrisonRegisterService.spec.ts
server/services/prison/PrisonRegisterService.ts
server/services/prison/PrisonTypes.ts

This PR wires in the PrisonRegisterStore into the PrisonRegisterService, so that the active prisons are cached in the store (redis)

SLM-73: Use the PrisonRegisterStore to cache active prisons in PrisonRegisterService

---

README.md
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
server/config.ts
server/routes/barcode/FindRecipientController.test.ts
server/routes/barcode/FindRecipientController.ts
server/services/prison/PrisonRegisterService.spec.ts
server/services/prison/PrisonRegisterService.ts

This PR enables support for an environment variable to filter the list of prisons presented on screen. This allows us to roll out the service to Legal Senders who interact with a subset of all prisons.

SLM-73: Added filtering for active prison values to enable/disable prisons in deployed environment

---

assets/sass/application-ie8.sass
assets/sass/application.sass
assets/sass/components/_scan-barcode-result.scss
integration_tests/integration/e2e/mailroomJourneyE2e.spec.ts
integration_tests/integration/scan/manuallyEnterBarcode.spec.ts
integration_tests/integration/scan/scanBarcode.spec.ts
integration_tests/integration/scan/scanBarcodeResult.spec.ts
server/views/pages/scan/scan-barcode-result.njk
server/views/pages/scan/scan-barcode-result.test.ts
server/views/partials/scan/scan-barcode-result-cannot-enter-barcode.njk
server/views/partials/scan/scan-barcode-result-duplicate.njk
server/views/partials/scan/scan-barcode-result-expired.njk
server/views/partials/scan/scan-barcode-result-further-checks-needed.njk
server/views/partials/scan/scan-barcode-result-not-found.njk
server/views/partials/scan/scan-barcode-result-ok.njk
server/views/partials/scan/scan-barcode-result-random-check.njk

This PR updates the Scan Results pages with the new content.
It does not replace the 'scan another barcode' form with the new 'Scan Another Barcode' button - that will be in the next PR. All this PR does is update the main content for each of the results pages - a few screenshots attached:

SLM-74 scan results page changes

---

assets/sass/components/_scan-barcode-form.scss
integration_tests/integration/e2e/mailroomJourneyE2e.spec.ts
integration_tests/pages/scan/scanAnotherBarcode.ts
integration_tests/pages/scan/scanBarcodeResult.ts
server/@types/express/index.d.ts
server/routes/scan/ScanBarcodeController.ts
server/views/pages/scan/scan-another-barcode.njk
server/views/pages/scan/scan-barcode-result.njk

This PR replaces the "scan another barcode" form at the bottom of each results screen with a "scan another barcode" button which takes the user to a different screen to do the barcode scanning from.
rcode Page

SLM-74: Replaced "scan another" form on bottom of results page with "scan another" button

---

integration_tests/integration/scan/scanBarcode.spec.ts
server/utils/nunjucksSetup.ts
server/views/partials/scan/scan-barcode-result-random-check.njk

Updated the text ('xray' → ‘X-ray’ and ‘Check Rule 39 Mail’ → ‘Check Rule 39 mail’) as requested:

SLM-74: Corrected typos identified as part of testing

---

server/routes/barcode/GenerateBarcodeImageController.test.ts
server/routes/barcode/GenerateBarcodeImageController.ts
server/routes/barcode/GenerateBarcodeImageView.ts
server/services/barcode/CreateBarcodeService.test.ts
server/services/barcode/CreateBarcodeService.ts

Refactored `CreateBarcodeService` so that there is only one public method, meaning consumers of this service do not need to know which methods to call in which order.

SLM-66: Refactored CreateBarcodeService as an enabler for PDF work

---

assets/sass/application-ie8.sass
assets/sass/application.sass
assets/sass/components/_select-envelope-size-form.scss
server/filters/renderEnvelopeSizeRadiosFilter.ts
server/middleware/barcode/setupBarcode.ts
server/routes/barcode/ChooseBarcodeOptionController.test.ts
server/routes/barcode/ChooseBarcodeOptionController.ts
server/routes/barcode/PdfController.test.ts
server/routes/barcode/PdfController.ts
server/utils/nunjucksSetup.ts
server/views/pages/barcode/pdf/select-envelope-size.njk

PR that adds the initial "Select Envelope Size" route and page (Temporary button to get to the page from "Review Recipients"; no POST endpoint for it to submit choice at this stage)

SLM-66: Added 'Select Envelope Size' page

---

server/services/barcode/CreateBarcodeService.ts

The existing transparent background has caused confusion during testing.

SLM-69 Put a white background behind the barcode address

---

server/middleware/setUpAuthentication.ts

See the `Custom Callback` section on https://www.passportjs.org/docs/authenticate/ for details on the callback.

Add additional logging for when the callback from HMPPS Auth fails

---

assets/js/page-enhancements.js
integration_tests/integration/barcode/createNewContact.spec.ts
integration_tests/pages/barcode/createNewContact.ts
server/views/pages/barcode/create-new-contact.njk

This PR fixes SLM-94 which is the bug with autocomplete where blanking a previous valid valid, or changing a previous valid value to a non-matching value results in the previous value being submitted on the form.
As part of implementing the fix I have written a couple of cypress tests which assert the prison name field has the error highlight and message when in error, so I have also had to fix SLM-92 as part of this.

SLM-94: Fix prison name autocomplete when either blank or non-matching prison name is selected

---

README.md
integration_tests/mockApis/sendLegalMail.ts
server/@types/express/index.d.ts
server/@types/forms/index.d.ts
server/app.ts
server/index.ts
server/middleware/barcode/setupBarcode.ts
server/routes/barcode/contacts/ChooseContactController.test.ts
server/routes/barcode/contacts/ChooseContactController.ts
server/routes/barcode/contacts/CreateContactByPrisonNumberController.test.ts
server/routes/barcode/contacts/CreateContactByPrisonNumberController.ts
server/routes/barcode/contacts/CreateContactByPrisonerNameController.test.ts
server/routes/barcode/contacts/CreateContactByPrisonerNameController.ts
server/routes/barcode/recipients/FindRecipientController.test.ts
server/routes/barcode/recipients/FindRecipientController.ts
server/routes/barcode/recipients/RecipientFormService.test.ts
server/routes/barcode/recipients/RecipientFormService.ts

* Use a hidden RecipientForm to collect all recipient details between pages
* Hide all pages from each other
* Add a service for common RecipientForm functionality
* Refactor everything to use the new RecipientFormService
* And some readme updates

SLM-62 reafactor recipients

---

integration_tests/integration/helpdesk/contactHelpdelpdesk.spec.ts
integration_tests/pages/authorisationError.ts
server/app.ts
server/middleware/authorisationMiddleware.test.ts
server/middleware/authorisationMiddleware.ts
server/middleware/helpdesk/contactHelpdeskAuthorisationMiddleware.test.ts
server/middleware/helpdesk/contactHelpdeskAuthorisationMiddleware.ts
server/utils/nunjucksSetup.ts
server/views/autherror.njk

This PR sets up the authentication and authorisation rules for the `/scan-barcode/contact-helpdesk` route:
When requesting `scan-barcode/contact-helpdesk`:
* If you are not DPS authenticated at all, show the AuthError page
* If you are DPS authenticated but do not have either of the SLM roles, show the AuthError page
Also updated the markup of the AuthError page in line with the current design

SLM-153: Authentication & Authorisation for contact helpdesk; AuthError page

---

server/views/layout.njk

Feedback banner content updated as required:

SLM-133: Updated feedback banner content

---

integration_tests/integration/barcode/editContact.spec.ts
server/routes/barcode/review/ReviewRecipientsController.test.ts
server/routes/barcode/review/ReviewRecipientsController.ts

Fixes bug where validation errors and previous "edit contact form" state are not cleared/reset when using the browser back button and then editing the contact again

SLM-175: Reset editContactForm when rendering review recipients page

---

server/@types/express/index.d.ts
server/authentication/auth.ts
server/routes/barcode/pdf/PdfController.ts
server/routes/barcode/pdf/PdfControllerView.ts
server/routes/link/RequestLinkController.ts
server/views/pages/barcode/pdf/print-coversheets.njk

Add barcopde number to screen when running the LSJ smoketest so it can be used in the LSJ smoketest.

SLM-190 Support smoke test

---

server/services/prison/prisonAddressData.json

Updated prison addresses for Holme House and Leeds. Changes to Risley and Swaleside were not required.
These are address labels using the new addresses:

SLM-180: Updated prison addresses for HHI and LEI

---

feature.env
server/routes/fixtures/SuperTestWrapper.ts

This PR fixes a couple of tests by forcing the One Time Code feature flag to be disabled.
This is necessary because at this stage of the development I have no tests for the One Time Code stuff that is dependant on the feature flag, but there are tests for the existing magic code auth approach that are now sensitive to the feature flag.
On my dev machine, where I am toggling the feature flag, the tests fail when I have left the feature flag on (ie. One Time Code enabled), so this change fixes that by forcing the flag off.
As and when the development for this One Time Code stuff matures we will write cypress and other SuperTest tests that properly test the journey with One Time Code enabled, but for the time being we can force it as disabled to keep the existing tests working

SLM-231: Set OTC feature flag to get tests running consistently

---

server/routes/one-time-code-auth/RequestOneTimeCodeController.test.ts
server/routes/one-time-code-auth/RequestOneTimeCodeController.ts
server/services/one-time-code-auth/OneTimeCodeService.test.ts
server/services/one-time-code-auth/OneTimeCodeService.ts
server/views/pages/one-time-code-auth/emailSent.njk

PR that implements the method in `OneTimeCodeService` to call the API to submit the user's email address and request a one time code is generated and emailed to them.
Wired into the controller, and tests implemented

SLM-231: Fleshed out service call to submit email to request a one time code

---

integration_tests/index.d.ts
integration_tests/pages/barcode/printCoversheets.ts
integration_tests/pages/one-time-code/requestOneTimeCode.ts
integration_tests/smoke/smoke.spec.ts
integration_tests/support/commands.ts
server/views/pages/barcode/pdf/print-coversheets.njk
smoke_tests/run-smoke-test.sh

PR to make our smoke tests aware of whether the environment under test is configured for One Time Code or not, and authenticate as the Smoke Test Legal Sender using the appropriate screens.

SLM-231: Smoke tests are now aware of and work with One Time Code

---

server/services/barcode/CreateBarcodeService.test.ts
server/services/barcode/CreateBarcodeService.ts

Removes any nulls from an address prior to producing the address label:

SLM-195: Remove nulls from an address

---

.circleci/config.yml

This is the fix to a horrible issue we've been suffering where the node app crashed with a segmentation fault when the integration tests started. It appears there was something in the cache that was missing - restoring the cache before running the node app fixed it 🥳

SLM-245 restore cache before running app for int tests

---

server/app.ts
server/filters/prisonsTableRowFilter.test.ts
server/filters/prisonsTableRowsFilter.ts
server/index.ts
server/middleware/prisons/setupSupportedPrisons.ts
server/routes/prisons/SupportedPrisonsController.test.ts
server/routes/prisons/SupportedPrisonsController.ts
server/routes/prisons/SupportedPrisonsView.ts
server/utils/nunjucksSetup.ts
server/views/pages/prisons/supported-prisons.njk
server/views/pages/prisons/supported-prisons.test.ts

Display supported prisons and allow add/remove.
**TODO**
* make add prison input a select containing prisons not yet added
* show prison name
* tidy up error handling
* replace existing supported prison config with prisons selected
* add some integration tests

SLM-253 Basic manage supported prison page

---

server/app.ts
server/index.ts
server/middleware/barcode/setupBarcode.ts
server/middleware/populateCurrentUser.ts
server/middleware/prisons/setupSupportedPrisons.ts
server/middleware/scan/setupScanBarcode.ts
server/middleware/start/setupLegalSenderStartPage.ts
server/routes/barcode/contacts/CreateContactByPrisonNumberController.test.ts
server/routes/barcode/contacts/CreateContactByPrisonNumberController.ts
server/routes/barcode/contacts/CreateContactByPrisonerNameController.test.ts
server/routes/barcode/contacts/CreateContactByPrisonerNameController.ts
server/routes/barcode/contacts/EditContactController.test.ts
server/routes/barcode/contacts/EditContactController.ts
server/routes/barcode/review/ReviewRecipientsController.test.ts
server/routes/barcode/review/ReviewRecipientsController.ts
server/routes/prisons/SupportedPrisonsController.test.ts
server/routes/prisons/SupportedPrisonsController.ts
server/routes/scan/VerifyBarcodeErrorResponseMapper.test.ts
server/routes/scan/VerifyBarcodeErrorResponseMapper.ts
server/routes/standardRouter.ts
server/routes/start/StartPageController.test.ts
server/routes/start/StartPageController.ts
server/routes/testutils/appSetup.ts
server/services/prison/PrisonService.ts

This looks big but it's all just replacing PrisonRegisterService and SupportedPrisonsService with the new facade PrisonService.
Once this is merged it'll be easier to replace all the code that uses `config.supportedPrisons` to filter out unsupported prisons.

SLM-253 Make PrisonService the single access point to services/prisons

---

helm_deploy/send-legal-mail-to-prisons/templates/ingress.yaml

Update ingress.yaml file as mentioned here - https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/apiversion-changes-ingress-k8s-1-22.html as part of prerequisite for switching ingress to the new nginx-ingress-controller v1.2.

Update ingress.yaml as prerequisite to switching ingress to new controller.

---

helm_deploy/send-legal-mail-to-prisons/Chart.yaml
helm_deploy/send-legal-mail-to-prisons/templates/ingress_v1_2.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Step 2 of switch to the new nginx-ingress-controller v1.2. as mentioned here - https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/Switch-ingress-to-v1-ingress-controller.html#step-2-create-a-new-ingress-resource.

Step 2 of switch to the new nginx-ingress-controller v1.2

---

.circleci/config.yml
.husky/pre-commit
package-lock.json
package.json
server/data/healthCheck.test.ts
server/services/cjsm/CjsmService.test.ts

* Bring over recent changes from the template project to speed up Jest.
* Remove custom test runner, `jest-jasmine2` - which looks to have been added early in the project to [work around a bug](https://github.com/ministryofjustice/send-legal-mail-to-prisons/pull/222#discussion_r821771900) but is no longer needed.
* Tweak a few tests to prevent warnings about open handles being left on test runs
Performance improvements (running locally):
**Before**
```bash
Test Suites: 109 passed, 109 total
Tests:       598 passed, 598 total
Snapshots:   0 total
Time:        28.109 s, estimated 35 s
```
**After**
```bash
Test Suites: 109 passed, 109 total
Tests:       598 passed, 598 total
Snapshots:   0 total
Time:        7.582 s, estimated 14 s
```

Speed up Jest with changes from template project

---

.circleci/config.yml

Please refer to - https://github.com/npm/cli/issues/6051

Pin npm to 9.2.0 based on Tom's suggestion as a fix for build issues.

---

.circleci/config.yml

Reverts ministryofjustice/send-legal-mail-to-prisons#384
Issue with `npm` that required us to pin the version now looks to be fixed (https://github.com/npm/cli/releases/tag/v9.3.1)

Revert "Pin npm to 9.2.0 based on Tom's suggestion as a fix for build issues."

---

.circleci/config.yml
smoke_tests/cypress.config.ts
smoke_tests/run-smoke-test.sh

* Fix installation of `jq` dependency that was failing
* Remove unnecessary `baseUrl` config that was incorrectly overriding CI config
* Fix error in `run-smoke-tests.sh` that stopped build directory being deleted locally

SLM-270: Fix smoke tests in CircleCI

---

helm_deploy/send-legal-mail-to-prisons/Chart.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
2 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `30 => 22 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have …

Migrating project to use groups in allowlist
